name: Update README
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
