name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do código
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Gera o arquivo da animação
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: M2004GV # Substitua pelo seu nome de usuário
          grid_size: 50
          outputs: dist/snake.svg
          color_snake: "#FF5733"
          color_dots: "#FFC300"

      # 3. Adiciona e faz push do arquivo para o branch 'output'
      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
