name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: M2004GV
          outputs: dist/snake.svg
      - name: Push to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
