# This is a basic workflow to help you get started with Actions

name: Update Profile

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Update the profile
      - name: Update Profile
        run: |
          echo "### Last Updated: $(date)" >> README.md
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "Update README with latest date"
          git push
        env: # Set the GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
